package commons.messages;

import org.apache.commons.lang3.builder.ToStringBuilder;

import static org.apache.commons.lang3.builder.ToStringStyle.MULTI_LINE_STYLE;

public abstract class Message {
    // todo add id

    /**
     * This method generates a topic name (used for routing websocket messages) based on the simple name of the provided Message class.
     * The topic name is generated by converting the camel case of the class name to a hyphenated string.
     * For example, the class name "MyMessageClass" would be converted to "my-message-class".
     *
     * @param messageType the Message class to generate the topic name for
     * @return the generated topic name as a String
     */
    public static String getTopic(Class<? extends Message> messageType) {
        String name = messageType.getSimpleName();
        StringBuilder builder = new StringBuilder();

        for (int i = 0; i < name.length(); i++) {
            if (i > 0 && Character.isUpperCase(name.charAt(i))) {
                if (Character.isLowerCase(name.charAt(i-1)) ||
                    (i < name.length()-1 && Character.isLowerCase(name.charAt(i+1)))) {

                    builder.append("-");
                }
            }

            builder.append(Character.toLowerCase(name.charAt(i)));
        }

        return builder.toString();
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, MULTI_LINE_STYLE);
    }
}

